# ArgoCD Application Object

{{ with .Values }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }} # the name of service
  namespace: {{ .namespace }} # right now only argocd
  labels:
    app.kubernetes.io/name: {{ .name }} # the name of service
    app.kubernetes.io/part-of: {{ .repository }} # repositoryname (-deployment)(+root)
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with .finalizers }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  project: {{ .project }}
  {{- with .source }}
  source:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .sources }}
  sources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  destination:
    {{- toYaml .destination | nindent 4 }}
  {{- with .syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .info }}
  info:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
